-- RLS draft para desenvolvimento. Revisar e endurecer antes de produção.
-- A regra de ouro: usuário só acessa dados da empresa/concessionária/grupo permitido pelo perfil.
create or replace function public.current_profile_id() returns uuid language sql stable as $$ select auth.uid() $$;
alter table public."rv" enable row level security;
drop policy if exists "dev authenticated read rv" on public."rv";
create policy "dev authenticated read rv" on public."rv" for select to authenticated using (true);
drop policy if exists "dev authenticated write rv" on public."rv";
create policy "dev authenticated write rv" on public."rv" for all to authenticated using (true) with check (true);
alter table public."loh" enable row level security;
drop policy if exists "dev authenticated read loh" on public."loh";
create policy "dev authenticated read loh" on public."loh" for select to authenticated using (true);
drop policy if exists "dev authenticated write loh" on public."loh";
create policy "dev authenticated write loh" on public."loh" for all to authenticated using (true) with check (true);
alter table public."pais" enable row level security;
drop policy if exists "dev authenticated read pais" on public."pais";
create policy "dev authenticated read pais" on public."pais" for select to authenticated using (true);
drop policy if exists "dev authenticated write pais" on public."pais";
create policy "dev authenticated write pais" on public."pais" for all to authenticated using (true) with check (true);
alter table public."profiles" enable row level security;
drop policy if exists "dev authenticated read profiles" on public."profiles";
create policy "dev authenticated read profiles" on public."profiles" for select to authenticated using (true);
drop policy if exists "users update own profile" on public."profiles";
create policy "users update own profile" on public."profiles" for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
alter table public."debug" enable row level security;
drop policy if exists "dev authenticated read debug" on public."debug";
create policy "dev authenticated read debug" on public."debug" for select to authenticated using (true);
drop policy if exists "dev authenticated write debug" on public."debug";
create policy "dev authenticated write debug" on public."debug" for all to authenticated using (true) with check (true);
alter table public."grupo" enable row level security;
drop policy if exists "dev authenticated read grupo" on public."grupo";
create policy "dev authenticated read grupo" on public."grupo" for select to authenticated using (true);
drop policy if exists "dev authenticated write grupo" on public."grupo";
create policy "dev authenticated write grupo" on public."grupo" for all to authenticated using (true) with check (true);
alter table public."placar" enable row level security;
drop policy if exists "dev authenticated read placar" on public."placar";
create policy "dev authenticated read placar" on public."placar" for select to authenticated using (true);
drop policy if exists "dev authenticated write placar" on public."placar";
create policy "dev authenticated write placar" on public."placar" for all to authenticated using (true) with check (true);
alter table public."divisao" enable row level security;
drop policy if exists "dev authenticated read divisao" on public."divisao";
create policy "dev authenticated read divisao" on public."divisao" for select to authenticated using (true);
drop policy if exists "dev authenticated write divisao" on public."divisao";
create policy "dev authenticated write divisao" on public."divisao" for all to authenticated using (true) with check (true);
alter table public."empresa" enable row level security;
drop policy if exists "dev authenticated read empresa" on public."empresa";
create policy "dev authenticated read empresa" on public."empresa" for select to authenticated using (true);
drop policy if exists "dev authenticated write empresa" on public."empresa";
create policy "dev authenticated write empresa" on public."empresa" for all to authenticated using (true) with check (true);
alter table public."habitos" enable row level security;
drop policy if exists "dev authenticated read habitos" on public."habitos";
create policy "dev authenticated read habitos" on public."habitos" for select to authenticated using (true);
drop policy if exists "dev authenticated write habitos" on public."habitos";
create policy "dev authenticated write habitos" on public."habitos" for all to authenticated using (true) with check (true);
alter table public."rv_foco" enable row level security;
drop policy if exists "dev authenticated read rv_foco" on public."rv_foco";
create policy "dev authenticated read rv_foco" on public."rv_foco" for select to authenticated using (true);
drop policy if exists "dev authenticated write rv_foco" on public."rv_foco";
create policy "dev authenticated write rv_foco" on public."rv_foco" for all to authenticated using (true) with check (true);
alter table public."setores" enable row level security;
drop policy if exists "dev authenticated read setores" on public."setores";
create policy "dev authenticated read setores" on public."setores" for select to authenticated using (true);
drop policy if exists "dev authenticated write setores" on public."setores";
create policy "dev authenticated write setores" on public."setores" for all to authenticated using (true) with check (true);
alter table public."xr_acao" enable row level security;
drop policy if exists "dev authenticated read xr_acao" on public."xr_acao";
create policy "dev authenticated read xr_acao" on public."xr_acao" for select to authenticated using (true);
drop policy if exists "dev authenticated write xr_acao" on public."xr_acao";
create policy "dev authenticated write xr_acao" on public."xr_acao" for all to authenticated using (true) with check (true);
alter table public."xr_meta" enable row level security;
drop policy if exists "dev authenticated read xr_meta" on public."xr_meta";
create policy "dev authenticated read xr_meta" on public."xr_meta" for select to authenticated using (true);
drop policy if exists "dev authenticated write xr_meta" on public."xr_meta";
create policy "dev authenticated write xr_meta" on public."xr_meta" for all to authenticated using (true) with check (true);
alter table public."feedback" enable row level security;
drop policy if exists "dev authenticated read feedback" on public."feedback";
create policy "dev authenticated read feedback" on public."feedback" for select to authenticated using (true);
drop policy if exists "dev authenticated write feedback" on public."feedback";
create policy "dev authenticated write feedback" on public."feedback" for all to authenticated using (true) with check (true);
alter table public."rv_anexo" enable row level security;
drop policy if exists "dev authenticated read rv_anexo" on public."rv_anexo";
create policy "dev authenticated read rv_anexo" on public."rv_anexo" for select to authenticated using (true);
drop policy if exists "dev authenticated write rv_anexo" on public."rv_anexo";
create policy "dev authenticated write rv_anexo" on public."rv_anexo" for all to authenticated using (true) with check (true);
alter table public."grupo_ndp" enable row level security;
drop policy if exists "dev authenticated read grupo_ndp" on public."grupo_ndp";
create policy "dev authenticated read grupo_ndp" on public."grupo_ndp" for select to authenticated using (true);
drop policy if exists "dev authenticated write grupo_ndp" on public."grupo_ndp";
create policy "dev authenticated write grupo_ndp" on public."grupo_ndp" for all to authenticated using (true) with check (true);
alter table public."xr_placar" enable row level security;
drop policy if exists "dev authenticated read xr_placar" on public."xr_placar";
create policy "dev authenticated read xr_placar" on public."xr_placar" for select to authenticated using (true);
drop policy if exists "dev authenticated write xr_placar" on public."xr_placar";
create policy "dev authenticated write xr_placar" on public."xr_placar" for all to authenticated using (true) with check (true);
alter table public."instru_es" enable row level security;
drop policy if exists "dev authenticated read instru_es" on public."instru_es";
create policy "dev authenticated read instru_es" on public."instru_es" for select to authenticated using (true);
drop policy if exists "dev authenticated write instru_es" on public."instru_es";
create policy "dev authenticated write instru_es" on public."instru_es" for all to authenticated using (true) with check (true);
alter table public."indicadores" enable row level security;
drop policy if exists "dev authenticated read indicadores" on public."indicadores";
create policy "dev authenticated read indicadores" on public."indicadores" for select to authenticated using (true);
drop policy if exists "dev authenticated write indicadores" on public."indicadores";
create policy "dev authenticated write indicadores" on public."indicadores" for all to authenticated using (true) with check (true);
alter table public."agendamentos" enable row level security;
drop policy if exists "dev authenticated read agendamentos" on public."agendamentos";
create policy "dev authenticated read agendamentos" on public."agendamentos" for select to authenticated using (true);
drop policy if exists "dev authenticated write agendamentos" on public."agendamentos";
create policy "dev authenticated write agendamentos" on public."agendamentos" for all to authenticated using (true) with check (true);
alter table public."competencias" enable row level security;
drop policy if exists "dev authenticated read competencias" on public."competencias";
create policy "dev authenticated read competencias" on public."competencias" for select to authenticated using (true);
drop policy if exists "dev authenticated write competencias" on public."competencias";
create policy "dev authenticated write competencias" on public."competencias" for all to authenticated using (true) with check (true);
alter table public."faq_pergunta" enable row level security;
drop policy if exists "dev authenticated read faq_pergunta" on public."faq_pergunta";
create policy "dev authenticated read faq_pergunta" on public."faq_pergunta" for select to authenticated using (true);
drop policy if exists "dev authenticated write faq_pergunta" on public."faq_pergunta";
create policy "dev authenticated write faq_pergunta" on public."faq_pergunta" for all to authenticated using (true) with check (true);
alter table public."rv_auditoria" enable row level security;
drop policy if exists "dev authenticated read rv_auditoria" on public."rv_auditoria";
create policy "dev authenticated read rv_auditoria" on public."rv_auditoria" for select to authenticated using (true);
drop policy if exists "dev authenticated write rv_auditoria" on public."rv_auditoria";
create policy "dev authenticated write rv_auditoria" on public."rv_auditoria" for all to authenticated using (true) with check (true);
alter table public."solicitacoes" enable row level security;
drop policy if exists "dev authenticated read solicitacoes" on public."solicitacoes";
create policy "dev authenticated read solicitacoes" on public."solicitacoes" for select to authenticated using (true);
drop policy if exists "dev authenticated write solicitacoes" on public."solicitacoes";
create policy "dev authenticated write solicitacoes" on public."solicitacoes" for all to authenticated using (true) with check (true);
alter table public."xr_simulador" enable row level security;
drop policy if exists "dev authenticated read xr_simulador" on public."xr_simulador";
create policy "dev authenticated read xr_simulador" on public."xr_simulador" for select to authenticated using (true);
drop policy if exists "dev authenticated write xr_simulador" on public."xr_simulador";
create policy "dev authenticated write xr_simulador" on public."xr_simulador" for all to authenticated using (true) with check (true);
alter table public."rv_assinatura" enable row level security;
drop policy if exists "dev authenticated read rv_assinatura" on public."rv_assinatura";
create policy "dev authenticated read rv_assinatura" on public."rv_assinatura" for select to authenticated using (true);
drop policy if exists "dev authenticated write rv_assinatura" on public."rv_assinatura";
create policy "dev authenticated write rv_assinatura" on public."rv_assinatura" for all to authenticated using (true) with check (true);
alter table public."rv_modalidade" enable row level security;
drop policy if exists "dev authenticated read rv_modalidade" on public."rv_modalidade";
create policy "dev authenticated read rv_modalidade" on public."rv_modalidade" for select to authenticated using (true);
drop policy if exists "dev authenticated write rv_modalidade" on public."rv_modalidade";
create policy "dev authenticated write rv_modalidade" on public."rv_modalidade" for all to authenticated using (true) with check (true);
alter table public."slide_options" enable row level security;
drop policy if exists "dev authenticated read slide_options" on public."slide_options";
create policy "dev authenticated read slide_options" on public."slide_options" for select to authenticated using (true);
drop policy if exists "dev authenticated write slide_options" on public."slide_options";
create policy "dev authenticated write slide_options" on public."slide_options" for all to authenticated using (true) with check (true);
alter table public."xr_ano_fiscal" enable row level security;
drop policy if exists "dev authenticated read xr_ano_fiscal" on public."xr_ano_fiscal";
create policy "dev authenticated read xr_ano_fiscal" on public."xr_ano_fiscal" for select to authenticated using (true);
drop policy if exists "dev authenticated write xr_ano_fiscal" on public."xr_ano_fiscal";
create policy "dev authenticated write xr_ano_fiscal" on public."xr_ano_fiscal" for all to authenticated using (true) with check (true);
alter table public."concessionaria" enable row level security;
drop policy if exists "dev authenticated read concessionaria" on public."concessionaria";
create policy "dev authenticated read concessionaria" on public."concessionaria" for select to authenticated using (true);
drop policy if exists "dev authenticated write concessionaria" on public."concessionaria";
create policy "dev authenticated write concessionaria" on public."concessionaria" for all to authenticated using (true) with check (true);
alter table public."rr_indicadores" enable row level security;
drop policy if exists "dev authenticated read rr_indicadores" on public."rr_indicadores";
create policy "dev authenticated read rr_indicadores" on public."rr_indicadores" for select to authenticated using (true);
drop policy if exists "dev authenticated write rr_indicadores" on public."rr_indicadores";
create policy "dev authenticated write rr_indicadores" on public."rr_indicadores" for all to authenticated using (true) with check (true);
alter table public."placar_exclus_o" enable row level security;
drop policy if exists "dev authenticated read placar_exclus_o" on public."placar_exclus_o";
create policy "dev authenticated read placar_exclus_o" on public."placar_exclus_o" for select to authenticated using (true);
drop policy if exists "dev authenticated write placar_exclus_o" on public."placar_exclus_o";
create policy "dev authenticated write placar_exclus_o" on public."placar_exclus_o" for all to authenticated using (true) with check (true);
alter table public."rv_participante" enable row level security;
drop policy if exists "dev authenticated read rv_participante" on public."rv_participante";
create policy "dev authenticated read rv_participante" on public."rv_participante" for select to authenticated using (true);
drop policy if exists "dev authenticated write rv_participante" on public."rv_participante";
create policy "dev authenticated write rv_participante" on public."rv_participante" for all to authenticated using (true) with check (true);
alter table public."competencia_mapa" enable row level security;
drop policy if exists "dev authenticated read competencia_mapa" on public."competencia_mapa";
create policy "dev authenticated read competencia_mapa" on public."competencia_mapa" for select to authenticated using (true);
drop policy if exists "dev authenticated write competencia_mapa" on public."competencia_mapa";
create policy "dev authenticated write competencia_mapa" on public."competencia_mapa" for all to authenticated using (true) with check (true);
alter table public."rv_proximo_passo" enable row level security;
drop policy if exists "dev authenticated read rv_proximo_passo" on public."rv_proximo_passo";
create policy "dev authenticated read rv_proximo_passo" on public."rv_proximo_passo" for select to authenticated using (true);
drop policy if exists "dev authenticated write rv_proximo_passo" on public."rv_proximo_passo";
create policy "dev authenticated write rv_proximo_passo" on public."rv_proximo_passo" for all to authenticated using (true) with check (true);
alter table public."competencia_mapa1" enable row level security;
drop policy if exists "dev authenticated read competencia_mapa1" on public."competencia_mapa1";
create policy "dev authenticated read competencia_mapa1" on public."competencia_mapa1" for select to authenticated using (true);
drop policy if exists "dev authenticated write competencia_mapa1" on public."competencia_mapa1";
create policy "dev authenticated write competencia_mapa1" on public."competencia_mapa1" for all to authenticated using (true) with check (true);
alter table public."competencia_mapa2" enable row level security;
drop policy if exists "dev authenticated read competencia_mapa2" on public."competencia_mapa2";
create policy "dev authenticated read competencia_mapa2" on public."competencia_mapa2" for select to authenticated using (true);
drop policy if exists "dev authenticated write competencia_mapa2" on public."competencia_mapa2";
create policy "dev authenticated write competencia_mapa2" on public."competencia_mapa2" for all to authenticated using (true) with check (true);
alter table public."dashboard_options" enable row level security;
drop policy if exists "dev authenticated read dashboard_options" on public."dashboard_options";
create policy "dev authenticated read dashboard_options" on public."dashboard_options" for select to authenticated using (true);
drop policy if exists "dev authenticated write dashboard_options" on public."dashboard_options";
create policy "dev authenticated write dashboard_options" on public."dashboard_options" for all to authenticated using (true) with check (true);
alter table public."xr_tipo_indicador" enable row level security;
drop policy if exists "dev authenticated read xr_tipo_indicador" on public."xr_tipo_indicador";
create policy "dev authenticated read xr_tipo_indicador" on public."xr_tipo_indicador" for select to authenticated using (true);
drop policy if exists "dev authenticated write xr_tipo_indicador" on public."xr_tipo_indicador";
create policy "dev authenticated write xr_tipo_indicador" on public."xr_tipo_indicador" for all to authenticated using (true) with check (true);
alter table public."competencia_habito" enable row level security;
drop policy if exists "dev authenticated read competencia_habito" on public."competencia_habito";
create policy "dev authenticated read competencia_habito" on public."competencia_habito" for select to authenticated using (true);
drop policy if exists "dev authenticated write competencia_habito" on public."competencia_habito";
create policy "dev authenticated write competencia_habito" on public."competencia_habito" for all to authenticated using (true) with check (true);
alter table public."funcao_colaborador" enable row level security;
drop policy if exists "dev authenticated read funcao_colaborador" on public."funcao_colaborador";
create policy "dev authenticated read funcao_colaborador" on public."funcao_colaborador" for select to authenticated using (true);
drop policy if exists "dev authenticated write funcao_colaborador" on public."funcao_colaborador";
create policy "dev authenticated write funcao_colaborador" on public."funcao_colaborador" for all to authenticated using (true) with check (true);
alter table public."xr_resultado_final" enable row level security;
drop policy if exists "dev authenticated read xr_resultado_final" on public."xr_resultado_final";
create policy "dev authenticated read xr_resultado_final" on public."xr_resultado_final" for select to authenticated using (true);
drop policy if exists "dev authenticated write xr_resultado_final" on public."xr_resultado_final";
create policy "dev authenticated write xr_resultado_final" on public."xr_resultado_final" for all to authenticated using (true) with check (true);
alter table public."calibracao_resultado" enable row level security;
drop policy if exists "dev authenticated read calibracao_resultado" on public."calibracao_resultado";
create policy "dev authenticated read calibracao_resultado" on public."calibracao_resultado" for select to authenticated using (true);
drop policy if exists "dev authenticated write calibracao_resultado" on public."calibracao_resultado";
create policy "dev authenticated write calibracao_resultado" on public."calibracao_resultado" for all to authenticated using (true) with check (true);
alter table public."setor_concessionaria" enable row level security;
drop policy if exists "dev authenticated read setor_concessionaria" on public."setor_concessionaria";
create policy "dev authenticated read setor_concessionaria" on public."setor_concessionaria" for select to authenticated using (true);
drop policy if exists "dev authenticated write setor_concessionaria" on public."setor_concessionaria";
create policy "dev authenticated write setor_concessionaria" on public."setor_concessionaria" for all to authenticated using (true) with check (true);
alter table public."competencia_indicador" enable row level security;
drop policy if exists "dev authenticated read competencia_indicador" on public."competencia_indicador";
create policy "dev authenticated read competencia_indicador" on public."competencia_indicador" for select to authenticated using (true);
drop policy if exists "dev authenticated write competencia_indicador" on public."competencia_indicador";
create policy "dev authenticated write competencia_indicador" on public."competencia_indicador" for all to authenticated using (true) with check (true);
alter table public."competencia_calibracao" enable row level security;
drop policy if exists "dev authenticated read competencia_calibracao" on public."competencia_calibracao";
create policy "dev authenticated read competencia_calibracao" on public."competencia_calibracao" for select to authenticated using (true);
drop policy if exists "dev authenticated write competencia_calibracao" on public."competencia_calibracao";
create policy "dev authenticated write competencia_calibracao" on public."competencia_calibracao" for all to authenticated using (true) with check (true);
alter table public."xr_indicador_resultado" enable row level security;
drop policy if exists "dev authenticated read xr_indicador_resultado" on public."xr_indicador_resultado";
create policy "dev authenticated read xr_indicador_resultado" on public."xr_indicador_resultado" for select to authenticated using (true);
drop policy if exists "dev authenticated write xr_indicador_resultado" on public."xr_indicador_resultado";
create policy "dev authenticated write xr_indicador_resultado" on public."xr_indicador_resultado" for all to authenticated using (true) with check (true);
